# Generated by Django 5.0.4 on 2024-05-12 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_book_inventory_borrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrow',
            name='due_back',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_web.genre'),
        ),
    ]
