# Generated by Django 5.0.4 on 2024-05-24 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0005_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_web.book'),
        ),
        migrations.AlterField(
            model_name='history',
            name='event_type',
            field=models.CharField(choices=[('borrow', 'Borrowed'), ('buy', 'Bought'), ('add', 'Added'), ('return', 'Returned'), ('update', 'Updated')], max_length=10),
        ),
        migrations.AlterField(
            model_name='history',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='main_web.member'),
        ),
    ]
